name: Build and test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  macos11_test:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on macOS 11 Big Sur
        shell: bash
        run: |
          set -ex
          swift test

  macos10_15_test:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on macOS 10.15 Catalina
        shell: bash
        run: |
          set -ex
          swift test

  ubuntu_test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on Ubuntu 18.04
        shell: bash
        run: |
          set -ex
          swift test --enable-test-discovery

  ubuntu_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on Ubuntu 20.04
        shell: bash
        run: |
          set -ex
          swift test --enable-test-discovery
