name: Build and test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  macos_test:
    name: Test macOS
    strategy:
      matrix:
        macVersion: [11.0, 10.15]

    runs-on: macos-${{ macVersion }}

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on macOS ${{ macVersion }}
        shell: bash
        run: |
          set -ex
          swift test

  ubuntu_test:
    name: Test Ubuntu
    strategy:
      matrix:
        ubuntuVersion: [18.04, 20.04]

    runs-on: ubuntu-${{ ubuntuVersion }}

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on Ubuntu ${{ ubuntuVersion }}
        shell: bash
        run: |
          set -ex
          swift test --enable-test-discovery
